=== ansys/pyaedt/src/ansys/aedt/core/misc/config.schema.json
{
   "$id":"https://github.com/ansys/pyaedt/tree/main/pyaedt/generic/config.schema.json",
   "$schema":"https://json-schema.org/draft/2020-12/schema",
   "title":"Pyaedt configuration file schema.",
   "type":"object",
   "properties":{
      "general":{
         "type":"object",
         "description":"Model configuration meta-data.",
         "properties": {
            "pyaedt_version": {"type":  "string"},
            "model_units":
               {"type": "string",
                "enum": ["nm", "um", "mm", "in", "inches", "mil", "cm", "dm", "meter", "km"]
               },
            "design_name": {"type": "string"},
            "date": {"type":  "string", "format":  "date-time"},
            "object_mapping": {"type":  "object"},
            "output_variables": {"type":  "object"},
            "variables": {"type":  "object"},
            "postprocessing_variables": {"type":  "object"}
         }
      },
      "setups":{
         "type":"object",
         "description":"Solution setup configuration. Keys are setup names."
      },
      "boundaries":{
         "type":"object",
         "description":"Assignment of boundary conditions. Keys are boundary names."
      },
      "mesh":{
         "type":"object",
         "description":"Assignment of mesh operations."
      },
      "coordinatesystems":{
         "type":"object",
         "description":"Relative coordinate systems."
      },
      "materials":{
         "type":"object",
         "description":"Material definitions."
      },
      "objects":{
         "type":"object",
         "description":"Material assignment and rendering of objects."
      },
      "datasets":{
         "type":"array",
         "description":"List of datasets"
      },
      "monitors":{
         "type":"array"
      },
      "native components":{
         "type":"object",
         "description":"Icepak native components."
      }
   },
   "required":[
      "general"
   ]
}

=== ansys/pyaedt/src/ansys/aedt/core/extensions/icepak/load.json
{"objects": {}, "materials": {}, "boundaries": {"CPU": {"ID": 2, "BoundType": "Block", "IsComponent": false, "Objects": [150, 422], "ParentBndID": -1, "Block Type": "Solid", "Use External Conditions": false, "Use Total Power": true, "Total Power": "4W"}}, "general": {"object_mapping": {"12": ["Region", [80.0, 14.0, -55.0]], "10": ["Region", [-240.0, 14.0, -55.0]], "422": "CPU", "150": "KB", "178": "HEAT_SINK", "62": "MEMORY1", "90": "MEMORY1_1", "155": ["KB", [-153.6, 1.6, -102.0]], "6": "Region", "34": "SERIAL_PORT", "118": "CAPACITOR", "134": "CAPACITOR_1", "450": "ALPHA_MAIN_PCB", "498": "Box1", "554": "MeshRegion1_SubRegion", "582": "MeshRegion2_SubRegion"}}}
