=== ansys/pyaedt/pyaedt/misc/config.schema.json
{
   "$id":"https://github.com/ansys/pyaedt/tree/main/pyaedt/generic/config.schema.json",
   "$schema":"https://json-schema.org/draft/2020-12/schema",
   "title":"Pyaedt configuration file schema.",
   "type":"object",
   "properties":{
      "general":{
         "type":"object",
         "description":"Model configuration meta-data."
      },
      "setups":{
         "type":"object",
         "description":"Solution setup configuration. Keys are setup names."
      },
      "boundaries":{
         "type":"object",
         "description":"Assignment of boundary conditions. Keys are boundary names."
      },
      "mesh":{
         "type":"object",
         "description":"Assignment of mesh operations."
      },
      "coordinatesystems":{
         "type":"object",
         "description":"Relative coordinate systems."
      },
      "materials":{
         "type":"object",
         "description":"Material definitions."
      },
      "objects":{
         "type":"object",
         "description":"Material assignment and rendering of objects."
      },
      "datasets":{
         "type":"array",
         "description":"List of datasets"
      },
      "monitors":{
         "type":"array"
      },
      "native components":{
         "type":"object",
         "description":"Icepak native components."
      }
   },
   "required":[
      "general"
   ]
}

=== ansys/pyaedt/tests/system/extensions/load.json
{"objects": {}, "materials": {"Al-Extruded": {"CoordinateSystemType": "Cartesian", "BulkOrSurfaceType": 1, "PhysicsTypes": {"set": ["Thermal"]}, "AttachedData": {"MatAppearanceData": {"property_data": "appearance_data", "Red": 232, "Green": 235, "Blue": 235}}, "permittivity": "1", "permeability": "1", "conductivity": "0", "dielectric_loss_tangent": "0", "magnetic_loss_tangent": "0", "thermal_conductivity": "200", "mass_density": "2000", "specific_heat": "900", "youngs_modulus": "0", "poissons_ratio": "0", "thermal_expansion_coefficient": "0", "thermal_material_type": {"property_type": "ChoiceProperty", "Choice": "Solid"}, "diffusivity": "0.8", "molecular_mass": "0", "viscosity": "0", "clarity_type": {"property_type": "ChoiceProperty", "Choice": "Opaque"}}, "air": {"CoordinateSystemType": "Cartesian", "BulkOrSurfaceType": 1, "PhysicsTypes": {"set": ["Electromagnetic", "Thermal"]}, "AttachedData": {"MatAppearanceData": {"property_data": "appearance_data", "Red": 230, "Green": 230, "Blue": 230, "Transparency": 0.949999988079071}}, "permittivity": "1.0006", "permeability": "1.0000004", "conductivity": "0", "dielectric_loss_tangent": "0", "magnetic_loss_tangent": "0", "thermal_conductivity": "0.0261", "mass_density": "1.1614", "specific_heat": "1005", "youngs_modulus": "0", "poissons_ratio": "0", "thermal_expansion_coefficient": "0.00333", "thermal_material_type": {"property_type": "ChoiceProperty", "Choice": "Fluid"}, "diffusivity": "2.88e-05", "molecular_mass": "0.028966", "viscosity": "2e-06", "material_refractive_index": "1.000293", "clarity_type": {"property_type": "ChoiceProperty", "Choice": "Transparent"}}, "PCB_Material": {"CoordinateSystemType": "Cartesian", "BulkOrSurfaceType": 1, "PhysicsTypes": {"set": ["Thermal"]}, "AttachedData": {"MatAppearanceData": {"property_data": "appearance_data", "Red": 210, "Green": 105, "Blue": 30, "Transparency": 0.0}}, "permittivity": "1", "permeability": "1", "conductivity": "0", "dielectric_loss_tangent": "0", "magnetic_loss_tangent": "0", "thermal_conductivity": "0.01", "mass_density": "2", "specific_heat": "2", "youngs_modulus": "0", "poissons_ratio": "0", "thermal_expansion_coefficient": "1", "diffusivity": "0.8", "molecular_mass": "0", "viscosity": "0"}}, "boundaries": {"Source1": {"ID": 5, "BoundType": "Source", "IsComponent": false, "Faces": [155], "Thermal Condition": "Total Power", "Total Power": "1.5W", "Surface Heat": "0mW_per_m2", "Temperature": "AmbientTemp", "Radiation": {"Radiate": false}, "Voltage/Current - Enabled": false, "Voltage/Current Option": "Current", "Current": "0A", "Voltage": "0V"}, "CPU": {"ID": 2, "BoundType": "Block", "IsComponent": false, "Objects": [422, 150], "ParentBndID": -1, "Block Type": "Solid", "Use External Conditions": false, "Use Total Power": true, "Total Power": "2W"}, "Memory": {"ID": 3, "BoundType": "Block", "IsComponent": false, "Objects": [62, 90], "ParentBndID": -1, "Block Type": "Solid", "Use External Conditions": false, "Use Total Power": false, "Power Density": "2w_per_m3"}}, "general": {"object_mapping": {"12": ["Region", [80.0, 14.0, -55.0]], "10": ["Region", [-240.0, 14.0, -55.0]], "422": "CPU", "150": "KB", "178": "HEAT_SINK", "62": "MEMORY1", "90": "MEMORY1_1", "155": ["KB", [-153.6, 1.6, -102.0]], "6": "Region", "34": "SERIAL_PORT", "118": "CAPACITOR", "134": "CAPACITOR_1", "450": "ALPHA_MAIN_PCB", "498": "Box1", "554": "MeshRegion1_SubRegion", "582": "MeshRegion2_SubRegion"}}}
